[project]
name = "bsf-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lancedb>=0.21.2",
    "nicegui>=2.13.0",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "pylance>=0.25.2",
    "tantivy>=0.22.0",
]


